# Introduction to Numpy

In [4]:
import numpy as np

In [5]:
my_list = [10,30,40,50]

In [6]:
type(my_list)

list

In [7]:
my_array = np.array(my_list)

In [8]:
my_array

array([10, 30, 40, 50])

In [9]:
type(my_array)

numpy.ndarray

In [10]:
my_array.max()

np.int64(50)

In [11]:
my_array.sum()

np.int64(130)

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.random.random((5,5))

array([[0.86054956, 0.88967875, 0.74477529, 0.13073692, 0.61666844],
       [0.4520339 , 0.92154681, 0.21649911, 0.76742198, 0.04599431],
       [0.80677704, 0.34194155, 0.81546427, 0.67345194, 0.27686458],
       [0.89441512, 0.97701791, 0.08657938, 0.61554666, 0.82463867],
       [0.09062947, 0.89027272, 0.70170608, 0.36037382, 0.02961969]])

## Array Arithmetics

In [19]:
my_list_1 = [1,2,3]
my_list_2 = [4,5,6]

In [20]:
my_list_1 + my_list_2

[1, 2, 3, 4, 5, 6]

In [22]:
my_array_1 = np.array(my_list_1)
my_array_2 = np.array(my_list_2)

In [23]:
my_array_1 + my_array_2

array([5, 7, 9])

In [27]:
my_array_1 + np.ones(my_array_1.shape)

array([2., 3., 4.])

In [28]:
my_array_1 - my_array_2

array([-3, -3, -3])

In [29]:
my_array_1 * my_array_2

array([ 4, 10, 18])

In [30]:
my_array_1 / my_array_2

array([0.25, 0.4 , 0.5 ])

In [31]:
my_array_1 * 10

array([10, 20, 30])

In [32]:
my_array_1.min()

np.int64(1)

In [33]:
my_array_2.max()

np.int64(6)

In [35]:
my_array_2.shape

(3,)

## Indexing

In [41]:
my_array_3 = np.arange(0,20)

In [42]:
my_array_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
my_array_3[12]

np.int64(12)

In [43]:
my_array_3[5:10]

array([5, 6, 7, 8, 9])

In [53]:
my_array_3[2:15:3]

array([ 2,  5,  8, 11, 14])

In [46]:
my_array_3[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [52]:
my_array_3[-2:]

array([18, 19])

### random

In [55]:
np.random.randn(4,4)

array([[ 1.48754291, -1.1698088 ,  0.57367523,  1.24827587],
       [ 1.87678847, -0.95024546,  0.88050908,  0.66268331],
       [ 0.63882847, -0.66587308, -1.25343249,  0.46637788],
       [ 1.1959103 ,  1.30902461, -0.53368656,  1.15857655]])

In [56]:
np.random.randint(1,300,(5,4))

array([[156, 216, 252, 249],
       [255, 238, 255,  49],
       [237,  64, 120, 156],
       [251, 276, 220, 139],
       [227, 189,  85, 193]], dtype=int32)