In [2]:
import numpy as np

In [3]:
my_matrix = [[5,0],[10,20]]

In [4]:
my_matrix[0]

[5, 0]

In [5]:
my_matrix[0][0]

5

### Note : row by column (row,column)

In [9]:
np_matrix = np.array(my_matrix)

In [10]:
np_matrix

array([[ 5,  0],
       [10, 20]])

In [11]:
np_matrix[1][0]

np.int64(10)

In [12]:
np.zeros((8,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Matrix Arithmetics

In [14]:
array_1 = np.array([[10,20],[30,40]])
array_2 = np.array([[50,60],[70,80]])

In [16]:
array_1

array([[10, 20],
       [30, 40]])

In [18]:
array_2

array([[50, 60],
       [70, 80]])

In [15]:
array_1 + array_2

array([[ 60,  80],
       [100, 120]])

In [21]:
array_3 = np.array([90,100])

In [22]:
array_1 + array_3

array([[100, 120],
       [120, 140]])

In [23]:
array_1 * 2

array([[20, 40],
       [60, 80]])

## Matrix Multiplication

In [24]:
array_1

array([[10, 20],
       [30, 40]])

In [25]:
array_2

array([[50, 60],
       [70, 80]])

In [26]:
array_1 * array_2

array([[ 500, 1200],
       [2100, 3200]])

In [28]:
array_1 * array_3

array([[ 900, 2000],
       [2700, 4000]])

### dot product

In [34]:
array_4 = np.array([[1,2,3]])

In [35]:
array_4.shape

(1, 3)

In [36]:
array_5 = np.array([[2,3],[2,3],[2,3]])

In [37]:
array_5.shape

(3, 2)

In [38]:
array_4.dot(array_5)

array([[12, 18]])

In [39]:
array_4.dot(array_5).shape

(1, 2)