In [2]:
import numpy as np

In [3]:
array_1 = np.random.randint(1,100,20)

In [4]:
array_1

array([79, 41, 77, 51, 96, 80, 32, 30, 17, 26, 22, 67, 97,  8, 71, 41, 29,
       89, 52, 74], dtype=int32)

In [5]:
array_1 > 25

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [6]:
array_1[array_1 > 25]

array([79, 41, 77, 51, 96, 80, 32, 30, 26, 67, 97, 71, 41, 29, 89, 52, 74],
      dtype=int32)

## transpose & reshape

In [7]:
matrix = np.array([[10,20],[20,30],[30,40]])

In [8]:
matrix.shape

(3, 2)

In [9]:
matrix.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [10]:
matrix.T

array([[10, 20, 30],
       [20, 30, 40]])

In [12]:
matrix.T.shape

(2, 3)

In [13]:
random_array = np.random.random((6,1))

In [14]:
random_array

array([[0.2778302 ],
       [0.40687068],
       [0.1318286 ],
       [0.53836901],
       [0.81432028],
       [0.37486026]])

In [15]:
random_array.shape

(6, 1)

In [16]:
random_array_reshaped = random_array.reshape(3,2)

In [17]:
random_array_reshaped

array([[0.2778302 , 0.40687068],
       [0.1318286 , 0.53836901],
       [0.81432028, 0.37486026]])

In [18]:
random_array_reshaped.shape

(3, 2)

### z-score

In [19]:
data = np.array([10,12,13,15,18,25,100,105])

### outlier

In [20]:
mean = data.mean()

In [21]:
mean

np.float64(37.25)

In [22]:
data[data > mean]

array([100, 105])

In [23]:
std = data.std()

In [24]:
std

np.float64(37.9333296719389)

In [25]:
z_scores = (data - mean) / std

In [26]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [27]:
data[z_scores > 1]

array([100, 105])

### Math Equations

### 2x + 3y = 8 and 5x + 7y = 19

### coefficient

In [28]:
A = np.array([[2,3],[5,7]])

### constant

In [29]:
B = np.array([8,19])

In [30]:
solution = np.linalg.solve(A,B)

In [31]:
solution

array([1., 2.])